# environments/dev/backend.conf
resource_group_name  = "rg-terraform-state"
storage_account_name = "stfabricaccesstfstate"
container_name       = "tfstate"
key                  = "fabric-access-platform/dev.tfstate"
